// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/cls.proto

package com.yxf.tencentlog.proto;

public final class Cls {
  private Cls() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yxf.tencentlog.proto.Log)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 时间戳，UNIX时间格式
     * </pre>
     *
     * <code>required int64 time = 1;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <pre>
     * 时间戳，UNIX时间格式
     * </pre>
     *
     * <code>required int64 time = 1;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    java.util.List<Log.Content>
        getContentsList();
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    Log.Content getContents(int index);
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    int getContentsCount();
  }
  /**
   * Protobuf type {@code com.yxf.tencentlog.proto.Log}
   */
  public  static final class Log extends
      com.google.protobuf.GeneratedMessageLite<
          Log, Log.Builder> implements
      // @@protoc_insertion_point(message_implements:com.yxf.tencentlog.proto.Log)
      LogOrBuilder {
    private Log() {
      contents_ = emptyProtobufList();
    }
    public interface ContentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.yxf.tencentlog.proto.Log.Content)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       * @return Whether the key field is set.
       */
      boolean hasKey();
      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       * @return The key.
       */
      String getKey();
      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       * @return Whether the value field is set.
       */
      boolean hasValue();
      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       * @return The value.
       */
      String getValue();
      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       * @return The bytes for value.
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code com.yxf.tencentlog.proto.Log.Content}
     */
    public  static final class Content extends
        com.google.protobuf.GeneratedMessageLite<
            Content, Content.Builder> implements
        // @@protoc_insertion_point(message_implements:com.yxf.tencentlog.proto.Log.Content)
        ContentOrBuilder {
      private Content() {
        key_ = "";
        value_ = "";
      }
      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private String key_;
      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       * @return Whether the key field is set.
       */
      @Override
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       * @return The key.
       */
      @Override
      public String getKey() {
        return key_;
      }
      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       * @return The bytes for key.
       */
      @Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(key_);
      }
      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       * @param value The key to set.
       */
      private void setKey(
          String value) {
        Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
        key_ = value;
      }
      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       */
      private void clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
      }
      /**
       * <pre>
       * 每组字段的 key
       * </pre>
       *
       * <code>required string key = 1;</code>
       * @param value The bytes for key to set.
       */
      private void setKeyBytes(
          com.google.protobuf.ByteString value) {
        key_ = value.toStringUtf8();
        bitField0_ |= 0x00000001;
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private String value_;
      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       * @return Whether the value field is set.
       */
      @Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       * @return The value.
       */
      @Override
      public String getValue() {
        return value_;
      }
      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       * @return The bytes for value.
       */
      @Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(value_);
      }
      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       * @param value The value to set.
       */
      private void setValue(
          String value) {
        Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
        value_ = value;
      }
      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       */
      private void clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
      }
      /**
       * <pre>
       * 每组字段的 value
       * </pre>
       *
       * <code>required string value = 2;</code>
       * @param value The bytes for value to set.
       */
      private void setValueBytes(
          com.google.protobuf.ByteString value) {
        value_ = value.toStringUtf8();
        bitField0_ |= 0x00000002;
      }

      public static Content parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Content parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Content parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Content parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Content parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static Content parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static Content parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static Content parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static Content parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static Content parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static Content parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static Content parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(Content prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code com.yxf.tencentlog.proto.Log.Content}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            Content, Builder> implements
          // @@protoc_insertion_point(builder_implements:com.yxf.tencentlog.proto.Log.Content)
          ContentOrBuilder {
        // Construct using com.yxf.tencentlog.proto.Cls.Log.Content.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         * 每组字段的 key
         * </pre>
         *
         * <code>required string key = 1;</code>
         * @return Whether the key field is set.
         */
        @Override
        public boolean hasKey() {
          return instance.hasKey();
        }
        /**
         * <pre>
         * 每组字段的 key
         * </pre>
         *
         * <code>required string key = 1;</code>
         * @return The key.
         */
        @Override
        public String getKey() {
          return instance.getKey();
        }
        /**
         * <pre>
         * 每组字段的 key
         * </pre>
         *
         * <code>required string key = 1;</code>
         * @return The bytes for key.
         */
        @Override
        public com.google.protobuf.ByteString
            getKeyBytes() {
          return instance.getKeyBytes();
        }
        /**
         * <pre>
         * 每组字段的 key
         * </pre>
         *
         * <code>required string key = 1;</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            String value) {
          copyOnWrite();
          instance.setKey(value);
          return this;
        }
        /**
         * <pre>
         * 每组字段的 key
         * </pre>
         *
         * <code>required string key = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          copyOnWrite();
          instance.clearKey();
          return this;
        }
        /**
         * <pre>
         * 每组字段的 key
         * </pre>
         *
         * <code>required string key = 1;</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setKeyBytes(value);
          return this;
        }

        /**
         * <pre>
         * 每组字段的 value
         * </pre>
         *
         * <code>required string value = 2;</code>
         * @return Whether the value field is set.
         */
        @Override
        public boolean hasValue() {
          return instance.hasValue();
        }
        /**
         * <pre>
         * 每组字段的 value
         * </pre>
         *
         * <code>required string value = 2;</code>
         * @return The value.
         */
        @Override
        public String getValue() {
          return instance.getValue();
        }
        /**
         * <pre>
         * 每组字段的 value
         * </pre>
         *
         * <code>required string value = 2;</code>
         * @return The bytes for value.
         */
        @Override
        public com.google.protobuf.ByteString
            getValueBytes() {
          return instance.getValueBytes();
        }
        /**
         * <pre>
         * 每组字段的 value
         * </pre>
         *
         * <code>required string value = 2;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
            String value) {
          copyOnWrite();
          instance.setValue(value);
          return this;
        }
        /**
         * <pre>
         * 每组字段的 value
         * </pre>
         *
         * <code>required string value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          copyOnWrite();
          instance.clearValue();
          return this;
        }
        /**
         * <pre>
         * 每组字段的 value
         * </pre>
         *
         * <code>required string value = 2;</code>
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setValueBytes(value);
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.yxf.tencentlog.proto.Log.Content)
      }
      private byte memoizedIsInitialized = 2;
      @Override
      @SuppressWarnings({"unchecked", "fallthrough"})
      protected final Object dynamicMethod(
          MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new Content();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              Object[] objects = new Object[] {
                "bitField0_",
                "key_",
                "value_",
              };
              String info =
                  "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u1508\u0000\u0002" +
                  "\u1508\u0001";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<Content> parser = PARSER;
            if (parser == null) {
              synchronized (Content.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<Content>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return memoizedIsInitialized;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:com.yxf.tencentlog.proto.Log.Content)
      private static final Content DEFAULT_INSTANCE;
      static {
        Content defaultInstance = new Content();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          Content.class, defaultInstance);
      }

      public static Content getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Content> PARSER;

      public static com.google.protobuf.Parser<Content> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <pre>
     * 时间戳，UNIX时间格式
     * </pre>
     *
     * <code>required int64 time = 1;</code>
     * @return Whether the time field is set.
     */
    @Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 时间戳，UNIX时间格式
     * </pre>
     *
     * <code>required int64 time = 1;</code>
     * @return The time.
     */
    @Override
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     * 时间戳，UNIX时间格式
     * </pre>
     *
     * <code>required int64 time = 1;</code>
     * @param value The time to set.
     */
    private void setTime(long value) {
      bitField0_ |= 0x00000001;
      time_ = value;
    }
    /**
     * <pre>
     * 时间戳，UNIX时间格式
     * </pre>
     *
     * <code>required int64 time = 1;</code>
     */
    private void clearTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      time_ = 0L;
    }

    public static final int CONTENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<Content> contents_;
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    @Override
    public java.util.List<Content> getContentsList() {
      return contents_;
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    public java.util.List<? extends ContentOrBuilder>
        getContentsOrBuilderList() {
      return contents_;
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    @Override
    public int getContentsCount() {
      return contents_.size();
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    @Override
    public Content getContents(int index) {
      return contents_.get(index);
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    public ContentOrBuilder getContentsOrBuilder(
        int index) {
      return contents_.get(index);
    }
    private void ensureContentsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<Content> tmp = contents_;
      if (!tmp.isModifiable()) {
        contents_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    private void setContents(
        int index, Content value) {
      value.getClass();
  ensureContentsIsMutable();
      contents_.set(index, value);
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    private void addContents(Content value) {
      value.getClass();
  ensureContentsIsMutable();
      contents_.add(value);
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    private void addContents(
        int index, Content value) {
      value.getClass();
  ensureContentsIsMutable();
      contents_.add(index, value);
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    private void addAllContents(
        Iterable<? extends Content> values) {
      ensureContentsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, contents_);
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    private void clearContents() {
      contents_ = emptyProtobufList();
    }
    /**
     * <pre>
     * 一条日志里的多个kv组合
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
     */
    private void removeContents(int index) {
      ensureContentsIsMutable();
      contents_.remove(index);
    }

    public static Log parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Log parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Log parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Log parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Log parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Log parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Log parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Log parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Log parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Log parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Log parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Log parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Log prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.yxf.tencentlog.proto.Log}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Log, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yxf.tencentlog.proto.Log)
        LogOrBuilder {
      // Construct using com.yxf.tencentlog.proto.Cls.Log.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 时间戳，UNIX时间格式
       * </pre>
       *
       * <code>required int64 time = 1;</code>
       * @return Whether the time field is set.
       */
      @Override
      public boolean hasTime() {
        return instance.hasTime();
      }
      /**
       * <pre>
       * 时间戳，UNIX时间格式
       * </pre>
       *
       * <code>required int64 time = 1;</code>
       * @return The time.
       */
      @Override
      public long getTime() {
        return instance.getTime();
      }
      /**
       * <pre>
       * 时间戳，UNIX时间格式
       * </pre>
       *
       * <code>required int64 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        copyOnWrite();
        instance.setTime(value);
        return this;
      }
      /**
       * <pre>
       * 时间戳，UNIX时间格式
       * </pre>
       *
       * <code>required int64 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        copyOnWrite();
        instance.clearTime();
        return this;
      }

      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      @Override
      public java.util.List<Content> getContentsList() {
        return java.util.Collections.unmodifiableList(
            instance.getContentsList());
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      @Override
      public int getContentsCount() {
        return instance.getContentsCount();
      }/**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      @Override
      public Content getContents(int index) {
        return instance.getContents(index);
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder setContents(
          int index, Content value) {
        copyOnWrite();
        instance.setContents(index, value);
        return this;
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder setContents(
          int index, Content.Builder builderForValue) {
        copyOnWrite();
        instance.setContents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder addContents(Content value) {
        copyOnWrite();
        instance.addContents(value);
        return this;
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder addContents(
          int index, Content value) {
        copyOnWrite();
        instance.addContents(index, value);
        return this;
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder addContents(
          Content.Builder builderForValue) {
        copyOnWrite();
        instance.addContents(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder addContents(
          int index, Content.Builder builderForValue) {
        copyOnWrite();
        instance.addContents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder addAllContents(
          Iterable<? extends Content> values) {
        copyOnWrite();
        instance.addAllContents(values);
        return this;
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder clearContents() {
        copyOnWrite();
        instance.clearContents();
        return this;
      }
      /**
       * <pre>
       * 一条日志里的多个kv组合
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log.Content contents = 2;</code>
       */
      public Builder removeContents(int index) {
        copyOnWrite();
        instance.removeContents(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yxf.tencentlog.proto.Log)
    }
    private byte memoizedIsInitialized = 2;
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Log();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "time_",
              "contents_",
              Content.class,
            };
            String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0002\u0001\u1502\u0000\u0002" +
                "\u041b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Log> parser = PARSER;
          if (parser == null) {
            synchronized (Log.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Log>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.yxf.tencentlog.proto.Log)
    private static final Log DEFAULT_INSTANCE;
    static {
      Log defaultInstance = new Log();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Log.class, defaultInstance);
    }

    public static Log getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Log> PARSER;

    public static com.google.protobuf.Parser<Log> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LogTagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yxf.tencentlog.proto.LogTag)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string key = 1;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     * @return The key.
     */
    String getKey();
    /**
     * <code>required string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     * @return The value.
     */
    String getValue();
    /**
     * <code>required string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.yxf.tencentlog.proto.LogTag}
   */
  public  static final class LogTag extends
      com.google.protobuf.GeneratedMessageLite<
          LogTag, LogTag.Builder> implements
      // @@protoc_insertion_point(message_implements:com.yxf.tencentlog.proto.LogTag)
      LogTagOrBuilder {
    private LogTag() {
      key_ = "";
      value_ = "";
    }
    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private String key_;
    /**
     * <code>required string key = 1;</code>
     * @return Whether the key field is set.
     */
    @Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string key = 1;</code>
     * @return The key.
     */
    @Override
    public String getKey() {
      return key_;
    }
    /**
     * <code>required string key = 1;</code>
     * @return The bytes for key.
     */
    @Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(key_);
    }
    /**
     * <code>required string key = 1;</code>
     * @param value The key to set.
     */
    private void setKey(
        String value) {
      Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      key_ = value;
    }
    /**
     * <code>required string key = 1;</code>
     */
    private void clearKey() {
      bitField0_ = (bitField0_ & ~0x00000001);
      key_ = getDefaultInstance().getKey();
    }
    /**
     * <code>required string key = 1;</code>
     * @param value The bytes for key to set.
     */
    private void setKeyBytes(
        com.google.protobuf.ByteString value) {
      key_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private String value_;
    /**
     * <code>required string value = 2;</code>
     * @return Whether the value field is set.
     */
    @Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string value = 2;</code>
     * @return The value.
     */
    @Override
    public String getValue() {
      return value_;
    }
    /**
     * <code>required string value = 2;</code>
     * @return The bytes for value.
     */
    @Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>required string value = 2;</code>
     * @param value The value to set.
     */
    private void setValue(
        String value) {
      Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      value_ = value;
    }
    /**
     * <code>required string value = 2;</code>
     */
    private void clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>required string value = 2;</code>
     * @param value The bytes for value to set.
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      value_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static LogTag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogTag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogTag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogTag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogTag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogTag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogTag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LogTag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LogTag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LogTag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LogTag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LogTag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(LogTag prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.yxf.tencentlog.proto.LogTag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LogTag, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yxf.tencentlog.proto.LogTag)
        LogTagOrBuilder {
      // Construct using com.yxf.tencentlog.proto.Cls.LogTag.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string key = 1;</code>
       * @return Whether the key field is set.
       */
      @Override
      public boolean hasKey() {
        return instance.hasKey();
      }
      /**
       * <code>required string key = 1;</code>
       * @return The key.
       */
      @Override
      public String getKey() {
        return instance.getKey();
      }
      /**
       * <code>required string key = 1;</code>
       * @return The bytes for key.
       */
      @Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        return instance.getKeyBytes();
      }
      /**
       * <code>required string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          String value) {
        copyOnWrite();
        instance.setKey(value);
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        copyOnWrite();
        instance.clearKey();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setKeyBytes(value);
        return this;
      }

      /**
       * <code>required string value = 2;</code>
       * @return Whether the value field is set.
       */
      @Override
      public boolean hasValue() {
        return instance.hasValue();
      }
      /**
       * <code>required string value = 2;</code>
       * @return The value.
       */
      @Override
      public String getValue() {
        return instance.getValue();
      }
      /**
       * <code>required string value = 2;</code>
       * @return The bytes for value.
       */
      @Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>required string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yxf.tencentlog.proto.LogTag)
    }
    private byte memoizedIsInitialized = 2;
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LogTag();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "key_",
              "value_",
            };
            String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u1508\u0000\u0002" +
                "\u1508\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<LogTag> parser = PARSER;
          if (parser == null) {
            synchronized (LogTag.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<LogTag>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.yxf.tencentlog.proto.LogTag)
    private static final LogTag DEFAULT_INSTANCE;
    static {
      LogTag defaultInstance = new LogTag();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LogTag.class, defaultInstance);
    }

    public static LogTag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogTag> PARSER;

    public static com.google.protobuf.Parser<LogTag> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LogGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yxf.tencentlog.proto.LogGroup)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    java.util.List<Log>
        getLogsList();
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    Log getLogs(int index);
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    int getLogsCount();

    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     * @return Whether the contextFlow field is set.
     */
    boolean hasContextFlow();
    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     * @return The contextFlow.
     */
    String getContextFlow();
    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     * @return The bytes for contextFlow.
     */
    com.google.protobuf.ByteString
        getContextFlowBytes();

    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     * @return Whether the filename field is set.
     */
    boolean hasFilename();
    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     * @return The filename.
     */
    String getFilename();
    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     * @return Whether the source field is set.
     */
    boolean hasSource();
    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     * @return The source.
     */
    String getSource();
    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     * @return The bytes for source.
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    java.util.List<LogTag>
        getLogTagsList();
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    LogTag getLogTags(int index);
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    int getLogTagsCount();
  }
  /**
   * Protobuf type {@code com.yxf.tencentlog.proto.LogGroup}
   */
  public  static final class LogGroup extends
      com.google.protobuf.GeneratedMessageLite<
          LogGroup, LogGroup.Builder> implements
      // @@protoc_insertion_point(message_implements:com.yxf.tencentlog.proto.LogGroup)
      LogGroupOrBuilder {
    private LogGroup() {
      logs_ = emptyProtobufList();
      contextFlow_ = "";
      filename_ = "";
      source_ = "";
      logTags_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int LOGS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Log> logs_;
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    @Override
    public java.util.List<Log> getLogsList() {
      return logs_;
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    public java.util.List<? extends LogOrBuilder>
        getLogsOrBuilderList() {
      return logs_;
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    @Override
    public int getLogsCount() {
      return logs_.size();
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    @Override
    public Log getLogs(int index) {
      return logs_.get(index);
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    public LogOrBuilder getLogsOrBuilder(
        int index) {
      return logs_.get(index);
    }
    private void ensureLogsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<Log> tmp = logs_;
      if (!tmp.isModifiable()) {
        logs_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    private void setLogs(
        int index, Log value) {
      value.getClass();
  ensureLogsIsMutable();
      logs_.set(index, value);
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    private void addLogs(Log value) {
      value.getClass();
  ensureLogsIsMutable();
      logs_.add(value);
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    private void addLogs(
        int index, Log value) {
      value.getClass();
  ensureLogsIsMutable();
      logs_.add(index, value);
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    private void addAllLogs(
        Iterable<? extends Log> values) {
      ensureLogsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, logs_);
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    private void clearLogs() {
      logs_ = emptyProtobufList();
    }
    /**
     * <pre>
     * 多条日志合成的日志数组
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
     */
    private void removeLogs(int index) {
      ensureLogsIsMutable();
      logs_.remove(index);
    }

    public static final int CONTEXTFLOW_FIELD_NUMBER = 2;
    private String contextFlow_;
    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     * @return Whether the contextFlow field is set.
     */
    @Override
    public boolean hasContextFlow() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     * @return The contextFlow.
     */
    @Override
    public String getContextFlow() {
      return contextFlow_;
    }
    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     * @return The bytes for contextFlow.
     */
    @Override
    public com.google.protobuf.ByteString
        getContextFlowBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(contextFlow_);
    }
    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     * @param value The contextFlow to set.
     */
    private void setContextFlow(
        String value) {
      Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      contextFlow_ = value;
    }
    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     */
    private void clearContextFlow() {
      bitField0_ = (bitField0_ & ~0x00000001);
      contextFlow_ = getDefaultInstance().getContextFlow();
    }
    /**
     * <pre>
     * 目前暂无效用
     * </pre>
     *
     * <code>optional string contextFlow = 2;</code>
     * @param value The bytes for contextFlow to set.
     */
    private void setContextFlowBytes(
        com.google.protobuf.ByteString value) {
      contextFlow_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int FILENAME_FIELD_NUMBER = 3;
    private String filename_;
    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     * @return Whether the filename field is set.
     */
    @Override
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     * @return The filename.
     */
    @Override
    public String getFilename() {
      return filename_;
    }
    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     * @return The bytes for filename.
     */
    @Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(filename_);
    }
    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     * @param value The filename to set.
     */
    private void setFilename(
        String value) {
      Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      filename_ = value;
    }
    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     */
    private void clearFilename() {
      bitField0_ = (bitField0_ & ~0x00000002);
      filename_ = getDefaultInstance().getFilename();
    }
    /**
     * <pre>
     * 日志文件名
     * </pre>
     *
     * <code>optional string filename = 3;</code>
     * @param value The bytes for filename to set.
     */
    private void setFilenameBytes(
        com.google.protobuf.ByteString value) {
      filename_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int SOURCE_FIELD_NUMBER = 4;
    private String source_;
    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     * @return Whether the source field is set.
     */
    @Override
    public boolean hasSource() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     * @return The source.
     */
    @Override
    public String getSource() {
      return source_;
    }
    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     * @return The bytes for source.
     */
    @Override
    public com.google.protobuf.ByteString
        getSourceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(source_);
    }
    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     * @param value The source to set.
     */
    private void setSource(
        String value) {
      Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
      source_ = value;
    }
    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     */
    private void clearSource() {
      bitField0_ = (bitField0_ & ~0x00000004);
      source_ = getDefaultInstance().getSource();
    }
    /**
     * <pre>
     * 日志来源，一般使用机器IP
     * </pre>
     *
     * <code>optional string source = 4;</code>
     * @param value The bytes for source to set.
     */
    private void setSourceBytes(
        com.google.protobuf.ByteString value) {
      source_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static final int LOGTAGS_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<LogTag> logTags_;
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    @Override
    public java.util.List<LogTag> getLogTagsList() {
      return logTags_;
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    public java.util.List<? extends LogTagOrBuilder>
        getLogTagsOrBuilderList() {
      return logTags_;
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    @Override
    public int getLogTagsCount() {
      return logTags_.size();
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    @Override
    public LogTag getLogTags(int index) {
      return logTags_.get(index);
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    public LogTagOrBuilder getLogTagsOrBuilder(
        int index) {
      return logTags_.get(index);
    }
    private void ensureLogTagsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<LogTag> tmp = logTags_;
      if (!tmp.isModifiable()) {
        logTags_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    private void setLogTags(
        int index, LogTag value) {
      value.getClass();
  ensureLogTagsIsMutable();
      logTags_.set(index, value);
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    private void addLogTags(LogTag value) {
      value.getClass();
  ensureLogTagsIsMutable();
      logTags_.add(value);
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    private void addLogTags(
        int index, LogTag value) {
      value.getClass();
  ensureLogTagsIsMutable();
      logTags_.add(index, value);
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    private void addAllLogTags(
        Iterable<? extends LogTag> values) {
      ensureLogTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, logTags_);
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    private void clearLogTags() {
      logTags_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
     */
    private void removeLogTags(int index) {
      ensureLogTagsIsMutable();
      logTags_.remove(index);
    }

    public static LogGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LogGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LogGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LogGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LogGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LogGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(LogGroup prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.yxf.tencentlog.proto.LogGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LogGroup, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yxf.tencentlog.proto.LogGroup)
        LogGroupOrBuilder {
      // Construct using com.yxf.tencentlog.proto.Cls.LogGroup.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      @Override
      public java.util.List<Log> getLogsList() {
        return java.util.Collections.unmodifiableList(
            instance.getLogsList());
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      @Override
      public int getLogsCount() {
        return instance.getLogsCount();
      }/**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      @Override
      public Log getLogs(int index) {
        return instance.getLogs(index);
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder setLogs(
          int index, Log value) {
        copyOnWrite();
        instance.setLogs(index, value);
        return this;
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder setLogs(
          int index, Log.Builder builderForValue) {
        copyOnWrite();
        instance.setLogs(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder addLogs(Log value) {
        copyOnWrite();
        instance.addLogs(value);
        return this;
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder addLogs(
          int index, Log value) {
        copyOnWrite();
        instance.addLogs(index, value);
        return this;
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder addLogs(
          Log.Builder builderForValue) {
        copyOnWrite();
        instance.addLogs(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder addLogs(
          int index, Log.Builder builderForValue) {
        copyOnWrite();
        instance.addLogs(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder addAllLogs(
          Iterable<? extends Log> values) {
        copyOnWrite();
        instance.addAllLogs(values);
        return this;
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder clearLogs() {
        copyOnWrite();
        instance.clearLogs();
        return this;
      }
      /**
       * <pre>
       * 多条日志合成的日志数组
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.Log logs = 1;</code>
       */
      public Builder removeLogs(int index) {
        copyOnWrite();
        instance.removeLogs(index);
        return this;
      }

      /**
       * <pre>
       * 目前暂无效用
       * </pre>
       *
       * <code>optional string contextFlow = 2;</code>
       * @return Whether the contextFlow field is set.
       */
      @Override
      public boolean hasContextFlow() {
        return instance.hasContextFlow();
      }
      /**
       * <pre>
       * 目前暂无效用
       * </pre>
       *
       * <code>optional string contextFlow = 2;</code>
       * @return The contextFlow.
       */
      @Override
      public String getContextFlow() {
        return instance.getContextFlow();
      }
      /**
       * <pre>
       * 目前暂无效用
       * </pre>
       *
       * <code>optional string contextFlow = 2;</code>
       * @return The bytes for contextFlow.
       */
      @Override
      public com.google.protobuf.ByteString
          getContextFlowBytes() {
        return instance.getContextFlowBytes();
      }
      /**
       * <pre>
       * 目前暂无效用
       * </pre>
       *
       * <code>optional string contextFlow = 2;</code>
       * @param value The contextFlow to set.
       * @return This builder for chaining.
       */
      public Builder setContextFlow(
          String value) {
        copyOnWrite();
        instance.setContextFlow(value);
        return this;
      }
      /**
       * <pre>
       * 目前暂无效用
       * </pre>
       *
       * <code>optional string contextFlow = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContextFlow() {
        copyOnWrite();
        instance.clearContextFlow();
        return this;
      }
      /**
       * <pre>
       * 目前暂无效用
       * </pre>
       *
       * <code>optional string contextFlow = 2;</code>
       * @param value The bytes for contextFlow to set.
       * @return This builder for chaining.
       */
      public Builder setContextFlowBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContextFlowBytes(value);
        return this;
      }

      /**
       * <pre>
       * 日志文件名
       * </pre>
       *
       * <code>optional string filename = 3;</code>
       * @return Whether the filename field is set.
       */
      @Override
      public boolean hasFilename() {
        return instance.hasFilename();
      }
      /**
       * <pre>
       * 日志文件名
       * </pre>
       *
       * <code>optional string filename = 3;</code>
       * @return The filename.
       */
      @Override
      public String getFilename() {
        return instance.getFilename();
      }
      /**
       * <pre>
       * 日志文件名
       * </pre>
       *
       * <code>optional string filename = 3;</code>
       * @return The bytes for filename.
       */
      @Override
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        return instance.getFilenameBytes();
      }
      /**
       * <pre>
       * 日志文件名
       * </pre>
       *
       * <code>optional string filename = 3;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          String value) {
        copyOnWrite();
        instance.setFilename(value);
        return this;
      }
      /**
       * <pre>
       * 日志文件名
       * </pre>
       *
       * <code>optional string filename = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        copyOnWrite();
        instance.clearFilename();
        return this;
      }
      /**
       * <pre>
       * 日志文件名
       * </pre>
       *
       * <code>optional string filename = 3;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFilenameBytes(value);
        return this;
      }

      /**
       * <pre>
       * 日志来源，一般使用机器IP
       * </pre>
       *
       * <code>optional string source = 4;</code>
       * @return Whether the source field is set.
       */
      @Override
      public boolean hasSource() {
        return instance.hasSource();
      }
      /**
       * <pre>
       * 日志来源，一般使用机器IP
       * </pre>
       *
       * <code>optional string source = 4;</code>
       * @return The source.
       */
      @Override
      public String getSource() {
        return instance.getSource();
      }
      /**
       * <pre>
       * 日志来源，一般使用机器IP
       * </pre>
       *
       * <code>optional string source = 4;</code>
       * @return The bytes for source.
       */
      @Override
      public com.google.protobuf.ByteString
          getSourceBytes() {
        return instance.getSourceBytes();
      }
      /**
       * <pre>
       * 日志来源，一般使用机器IP
       * </pre>
       *
       * <code>optional string source = 4;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(
          String value) {
        copyOnWrite();
        instance.setSource(value);
        return this;
      }
      /**
       * <pre>
       * 日志来源，一般使用机器IP
       * </pre>
       *
       * <code>optional string source = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        copyOnWrite();
        instance.clearSource();
        return this;
      }
      /**
       * <pre>
       * 日志来源，一般使用机器IP
       * </pre>
       *
       * <code>optional string source = 4;</code>
       * @param value The bytes for source to set.
       * @return This builder for chaining.
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSourceBytes(value);
        return this;
      }

      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      @Override
      public java.util.List<LogTag> getLogTagsList() {
        return java.util.Collections.unmodifiableList(
            instance.getLogTagsList());
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      @Override
      public int getLogTagsCount() {
        return instance.getLogTagsCount();
      }/**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      @Override
      public LogTag getLogTags(int index) {
        return instance.getLogTags(index);
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder setLogTags(
          int index, LogTag value) {
        copyOnWrite();
        instance.setLogTags(index, value);
        return this;
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder setLogTags(
          int index, LogTag.Builder builderForValue) {
        copyOnWrite();
        instance.setLogTags(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder addLogTags(LogTag value) {
        copyOnWrite();
        instance.addLogTags(value);
        return this;
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder addLogTags(
          int index, LogTag value) {
        copyOnWrite();
        instance.addLogTags(index, value);
        return this;
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder addLogTags(
          LogTag.Builder builderForValue) {
        copyOnWrite();
        instance.addLogTags(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder addLogTags(
          int index, LogTag.Builder builderForValue) {
        copyOnWrite();
        instance.addLogTags(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder addAllLogTags(
          Iterable<? extends LogTag> values) {
        copyOnWrite();
        instance.addAllLogTags(values);
        return this;
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder clearLogTags() {
        copyOnWrite();
        instance.clearLogTags();
        return this;
      }
      /**
       * <code>repeated .com.yxf.tencentlog.proto.LogTag logTags = 5;</code>
       */
      public Builder removeLogTags(int index) {
        copyOnWrite();
        instance.removeLogTags(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yxf.tencentlog.proto.LogGroup)
    }
    private byte memoizedIsInitialized = 2;
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LogGroup();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "bitField0_",
              "logs_",
              Log.class,
              "contextFlow_",
              "filename_",
              "source_",
              "logTags_",
              LogTag.class,
            };
            String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0002\u0002\u0001\u041b\u0002\u1008" +
                "\u0000\u0003\u1008\u0001\u0004\u1008\u0002\u0005\u041b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<LogGroup> parser = PARSER;
          if (parser == null) {
            synchronized (LogGroup.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<LogGroup>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.yxf.tencentlog.proto.LogGroup)
    private static final LogGroup DEFAULT_INSTANCE;
    static {
      LogGroup defaultInstance = new LogGroup();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LogGroup.class, defaultInstance);
    }

    public static LogGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogGroup> PARSER;

    public static com.google.protobuf.Parser<LogGroup> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LogGroupListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yxf.tencentlog.proto.LogGroupList)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    java.util.List<LogGroup>
        getLogGroupListList();
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    LogGroup getLogGroupList(int index);
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    int getLogGroupListCount();
  }
  /**
   * Protobuf type {@code com.yxf.tencentlog.proto.LogGroupList}
   */
  public  static final class LogGroupList extends
      com.google.protobuf.GeneratedMessageLite<
          LogGroupList, LogGroupList.Builder> implements
      // @@protoc_insertion_point(message_implements:com.yxf.tencentlog.proto.LogGroupList)
      LogGroupListOrBuilder {
    private LogGroupList() {
      logGroupList_ = emptyProtobufList();
    }
    public static final int LOGGROUPLIST_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<LogGroup> logGroupList_;
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    @Override
    public java.util.List<LogGroup> getLogGroupListList() {
      return logGroupList_;
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    public java.util.List<? extends LogGroupOrBuilder>
        getLogGroupListOrBuilderList() {
      return logGroupList_;
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    @Override
    public int getLogGroupListCount() {
      return logGroupList_.size();
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    @Override
    public LogGroup getLogGroupList(int index) {
      return logGroupList_.get(index);
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    public LogGroupOrBuilder getLogGroupListOrBuilder(
        int index) {
      return logGroupList_.get(index);
    }
    private void ensureLogGroupListIsMutable() {
      com.google.protobuf.Internal.ProtobufList<LogGroup> tmp = logGroupList_;
      if (!tmp.isModifiable()) {
        logGroupList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    private void setLogGroupList(
        int index, LogGroup value) {
      value.getClass();
  ensureLogGroupListIsMutable();
      logGroupList_.set(index, value);
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    private void addLogGroupList(LogGroup value) {
      value.getClass();
  ensureLogGroupListIsMutable();
      logGroupList_.add(value);
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    private void addLogGroupList(
        int index, LogGroup value) {
      value.getClass();
  ensureLogGroupListIsMutable();
      logGroupList_.add(index, value);
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    private void addAllLogGroupList(
        Iterable<? extends LogGroup> values) {
      ensureLogGroupListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, logGroupList_);
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    private void clearLogGroupList() {
      logGroupList_ = emptyProtobufList();
    }
    /**
     * <pre>
     * 日志组列表
     * </pre>
     *
     * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
     */
    private void removeLogGroupList(int index) {
      ensureLogGroupListIsMutable();
      logGroupList_.remove(index);
    }

    public static LogGroupList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogGroupList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogGroupList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogGroupList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogGroupList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LogGroupList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LogGroupList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LogGroupList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LogGroupList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LogGroupList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LogGroupList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LogGroupList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(LogGroupList prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.yxf.tencentlog.proto.LogGroupList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LogGroupList, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yxf.tencentlog.proto.LogGroupList)
        LogGroupListOrBuilder {
      // Construct using com.yxf.tencentlog.proto.Cls.LogGroupList.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      @Override
      public java.util.List<LogGroup> getLogGroupListList() {
        return java.util.Collections.unmodifiableList(
            instance.getLogGroupListList());
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      @Override
      public int getLogGroupListCount() {
        return instance.getLogGroupListCount();
      }/**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      @Override
      public LogGroup getLogGroupList(int index) {
        return instance.getLogGroupList(index);
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder setLogGroupList(
          int index, LogGroup value) {
        copyOnWrite();
        instance.setLogGroupList(index, value);
        return this;
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder setLogGroupList(
          int index, LogGroup.Builder builderForValue) {
        copyOnWrite();
        instance.setLogGroupList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder addLogGroupList(LogGroup value) {
        copyOnWrite();
        instance.addLogGroupList(value);
        return this;
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder addLogGroupList(
          int index, LogGroup value) {
        copyOnWrite();
        instance.addLogGroupList(index, value);
        return this;
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder addLogGroupList(
          LogGroup.Builder builderForValue) {
        copyOnWrite();
        instance.addLogGroupList(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder addLogGroupList(
          int index, LogGroup.Builder builderForValue) {
        copyOnWrite();
        instance.addLogGroupList(index,
            builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder addAllLogGroupList(
          Iterable<? extends LogGroup> values) {
        copyOnWrite();
        instance.addAllLogGroupList(values);
        return this;
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder clearLogGroupList() {
        copyOnWrite();
        instance.clearLogGroupList();
        return this;
      }
      /**
       * <pre>
       * 日志组列表
       * </pre>
       *
       * <code>repeated .com.yxf.tencentlog.proto.LogGroup logGroupList = 1;</code>
       */
      public Builder removeLogGroupList(int index) {
        copyOnWrite();
        instance.removeLogGroupList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.yxf.tencentlog.proto.LogGroupList)
    }
    private byte memoizedIsInitialized = 2;
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LogGroupList();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "logGroupList_",
              LogGroup.class,
            };
            String info =
                "\u0001\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0001\u0001\u041b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<LogGroupList> parser = PARSER;
          if (parser == null) {
            synchronized (LogGroupList.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<LogGroupList>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.yxf.tencentlog.proto.LogGroupList)
    private static final LogGroupList DEFAULT_INSTANCE;
    static {
      LogGroupList defaultInstance = new LogGroupList();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LogGroupList.class, defaultInstance);
    }

    public static LogGroupList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LogGroupList> PARSER;

    public static com.google.protobuf.Parser<LogGroupList> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
